/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  DataIntakeApi,
  DataUploadApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierDataIntakeCustom } from "./client-custom";

export class VisierDataIntake extends VisierDataIntakeCustom {
  readonly dataIntake: DataIntakeApi;
  readonly dataUpload: DataUploadApi;

  constructor(configurationParameters: ConfigurationParameters) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.dataIntake = new DataIntakeApi(configuration);
    this.dataUpload = new DataUploadApi(configuration);
  }

}
