/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Job
 */
export interface Job {
    /**
     * The job ID of the receiving job for the analytic tenant.
     * @type {string}
     * @memberof Job
     */
    'receivingJobId'?: string;
    /**
     * The analytic tenant code.
     * @type {string}
     * @memberof Job
     */
    'tenantCode'?: string;
    /**
     * The status of the receiving job for the analytic tenant.
     * @type {string}
     * @memberof Job
     */
    'status'?: string;
}

