/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ProcessingJob
 */
export interface ProcessingJob {
    /**
     * The job ID of the processing job for the analytic tenant.
     * @type {string}
     * @memberof ProcessingJob
     */
    'jobId'?: string;
    /**
     * The analytic tenant code.
     * @type {string}
     * @memberof ProcessingJob
     */
    'tenantCode'?: string;
    /**
     * The data version associated with the processing job.
     * @type {string}
     * @memberof ProcessingJob
     */
    'dataVersion'?: string;
    /**
     * The status of the receiving job for the analytic tenant.
     * @type {string}
     * @memberof ProcessingJob
     */
    'status'?: string;
    /**
     * A meaningful message about the processing job.
     * @type {string}
     * @memberof ProcessingJob
     */
    'message'?: string;
}

