/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Tenant } from './tenant';

/**
 * 
 * @export
 * @interface PushDataResponse
 */
export interface PushDataResponse {
    /**
     * The unique identifier associated with the transfer session.
     * @type {string}
     * @memberof PushDataResponse
     */
    'transferSessionId'?: string;
    /**
     * The unique sequence number associated with a batch of records.
     * @type {number}
     * @memberof PushDataResponse
     */
    'sequence'?: number;
    /**
     * The status of the data transfer.
     * @type {string}
     * @memberof PushDataResponse
     */
    'status'?: string;
    /**
     * Any additional information about the data transfer.
     * @type {string}
     * @memberof PushDataResponse
     */
    'message'?: string;
    /**
     * A list of strings representing the tenants that data was pushed to and their data transfer results.
     * @type {Array<Tenant>}
     * @memberof PushDataResponse
     */
    'tenants'?: Array<Tenant>;
}

