/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface PushDataCompleteRequest
 */
export interface PushDataCompleteRequest {
    /**
     * The unique identifier associated with the transfer session.
     * @type {string}
     * @memberof PushDataCompleteRequest
     */
    'transferSessionId'?: string;
    /**
     * If true, a processing job will be triggered after the receiving job successfully completes. This generates a new data version.
     * @type {boolean}
     * @memberof PushDataCompleteRequest
     */
    'processingData'?: boolean;
}

