/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Definition of the source column.
 * @export
 * @interface PushDataColumnDefinitionDTO
 */
export interface PushDataColumnDefinitionDTO {
    /**
     * The name of the column.
     * @type {string}
     * @memberof PushDataColumnDefinitionDTO
     */
    'columnName'?: string;
    /**
     * The data type associated with the column.
     * @type {string}
     * @memberof PushDataColumnDefinitionDTO
     */
    'dataType'?: string;
    /**
     * The expected format for datetime data types.
     * @type {Array<string>}
     * @memberof PushDataColumnDefinitionDTO
     */
    'dataFormats'?: Array<string>;
    /**
     * If true, the column value is required. If a column is mandatory, and the file is missing this column, the request will fail.
     * @type {boolean}
     * @memberof PushDataColumnDefinitionDTO
     */
    'isMandatory'?: boolean;
    /**
     * If true, the column allows an empty value for the record.
     * @type {boolean}
     * @memberof PushDataColumnDefinitionDTO
     */
    'allowEmpty'?: boolean;
    /**
     * The default value of the column.
     * @type {string}
     * @memberof PushDataColumnDefinitionDTO
     */
    'defaultValue'?: string;
}

