/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PushDataSourceDefinitionDTO } from './push-data-source-definition-dto';

/**
 * The existing sources.
 * @export
 * @interface PushDataSourceDefinitionsDTO
 */
export interface PushDataSourceDefinitionsDTO {
    /**
     * A list of objects representing the target sources for the request.
     * @type {Array<PushDataSourceDefinitionDTO>}
     * @memberof PushDataSourceDefinitionsDTO
     */
    'sources'?: Array<PushDataSourceDefinitionDTO>;
}

