/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { DataTransferResultDetail } from './data-transfer-result-detail';

/**
 * 
 * @export
 * @interface PushDataCancelResponse
 */
export interface PushDataCancelResponse {
    /**
     * A meaningful message about the transfer session.
     * @type {string}
     * @memberof PushDataCancelResponse
     */
    'message'?: string;
    /**
     * The unique identifier associated with the transfer session.
     * @type {string}
     * @memberof PushDataCancelResponse
     */
    'transferSessionId'?: string;
    /**
     * A list of objects representing the results of the transfer session.
     * @type {Array<DataTransferResultDetail>}
     * @memberof PushDataCancelResponse
     */
    'dataTransferResultDetails'?: Array<DataTransferResultDetail>;
    /**
     * The status of the transfer session. A cancelled session returns the status CANCELLED.
     * @type {string}
     * @memberof PushDataCancelResponse
     */
    'status'?: string;
}

