/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PushDataColumnDefinitionDTO } from './push-data-column-definition-dto';

/**
 * Details of each existing source.
 * @export
 * @interface PushDataSourceDefinitionDTO
 */
export interface PushDataSourceDefinitionDTO {
    /**
     * The unique identifier associated with the source.
     * @type {string}
     * @memberof PushDataSourceDefinitionDTO
     */
    'sourceId'?: string;
    /**
     * The object name of the source.
     * @type {string}
     * @memberof PushDataSourceDefinitionDTO
     */
    'name'?: string;
    /**
     * A list of objects representing the source columns.
     * @type {Array<PushDataColumnDefinitionDTO>}
     * @memberof PushDataSourceDefinitionDTO
     */
    'columns'?: Array<PushDataColumnDefinitionDTO>;
    /**
     * If true, the source is inherited by all analytic tenants.
     * @type {boolean}
     * @memberof PushDataSourceDefinitionDTO
     */
    'isInherited'?: boolean;
}

