/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Job } from './job';

/**
 * 
 * @export
 * @interface ReceivingJobStatusResponse
 */
export interface ReceivingJobStatusResponse {
    /**
     * The unique identifier associated with the receiving job.
     * @type {string}
     * @memberof ReceivingJobStatusResponse
     */
    'jobId'?: string;
    /**
     * The status of the receiving job.
     * @type {string}
     * @memberof ReceivingJobStatusResponse
     */
    'status'?: string;
    /**
     * The job ID of the receiving job that spawned this job.
     * @type {string}
     * @memberof ReceivingJobStatusResponse
     */
    'parentJobId'?: string;
    /**
     * The tenant code of the receiving job that spawned  this job.
     * @type {string}
     * @memberof ReceivingJobStatusResponse
     */
    'parentTenantCode'?: string;
    /**
     * A list of objects representing the receiving jobs to retrieve.
     * @type {Array<Job>}
     * @memberof ReceivingJobStatusResponse
     */
    'receivingJobs'?: Array<Job>;
}

