/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface Source
 */
export interface Source {
    /**
     * The unique identifier associated with the source that data was transferred to.
     * @type {string}
     * @memberof Source
     */
    'sourceId'?: string;
    /**
     * The object name of the source.
     * @type {string}
     * @memberof Source
     */
    'sourceName'?: string;
    /**
     * The size of the data transfer in bytes.
     * @type {string}
     * @memberof Source
     */
    'dataSize'?: string;
    /**
     * The number of rows in the data transfer.
     * @type {string}
     * @memberof Source
     */
    'rows'?: string;
    /**
     * The status of the data transfer for this source.
     * @type {string}
     * @memberof Source
     */
    'status'?: string;
    /**
     * A meaningful message about the data transfer.
     * @type {string}
     * @memberof Source
     */
    'message'?: string;
}

