/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface StartTransferResponse
 */
export interface StartTransferResponse {
    /**
     * The unique identifier associated with the transfer session.
     * @type {string}
     * @memberof StartTransferResponse
     */
    'transferSessionId'?: string;
}

