/*
Visier Data Intake APIs

Visier APIs for sending raw or untransformed source data to Visier

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Source } from './source';

/**
 * 
 * @export
 * @interface Tenant
 */
export interface Tenant {
    /**
     * The code of the tenant that data was transferred to. For example, WFF_j1r or WFF_j1r~c7o.
     * @type {string}
     * @memberof Tenant
     */
    'tenantCode'?: string;
    /**
     * The status of the data transfer for this tenant.
     * @type {string}
     * @memberof Tenant
     */
    'status'?: string;
    /**
     * A list of objects representing the sources that data was pushed to and their data transfer results.
     * @type {Array<Source>}
     * @memberof Tenant
     */
    'sources'?: Array<Source>;
}

